### PR TITLE
Enable scope overrides from request params

### PR DESCRIPTION
**Pull request by nbgoodall**
Hello hello,

I ran into a problem trying to override the `scope` parameter in the OAuth URL. This PR fixes that so you can call e.g. `azure_oauth_path scope: "openid email Calendars.Read"` without having to define it in the config.

Also added a little spec, any questions/issues let me know!

### CODE REVIEW

**Review by pond — APPROVED** [review]

**Comment by pond** [comment]
Thanks for the feature. I'm merging this into a feature branch so I can add documentation, since otherwise, nobody would ever really know that this was possible unless they very carefully read all the gem code!

**Comment by pond** [comment]
I do note, however, that I think this would've been possible already using a custom provider class:

https://github.com/RIPAGlobal/omniauth-azure-activedirectory-v2/tree/feature/scope-from-request?tab=readme-ov-file#dynamic-options-via-a-custom-provider-class

...via `def scope`, I think.

**Comment by pond** [comment]
Now available in v2.2.0 at https://rubygems.org/gems/omniauth-azure-activedirectory-v2.

**Comment by nbgoodall** [comment]
> Thanks for the feature. I'm merging this into a feature branch so I can add documentation, since otherwise, nobody would ever really know that this was possible unless they very carefully read all the gem code!

Thank you, @pond! Sorry about the missing docs, appreciate that.

**Pull request merged**
